# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  peer0.orgcontraloria.example.com:

networks:
  test:
    name: fabric_test

services:

  peer0.orgcontraloria.example.com:
    container_name: peer0.orgcontraloria.example.com
    privileged: true
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.orgcontraloria.example.com
      - CORE_PEER_ADDRESS=peer0.orgcontraloria.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgcontraloria.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgcontraloria.example.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgcontraloria.example.com:11051
      - CORE_PEER_LOCALMSPID=OrgcontraloriaMSP
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_CHAINCODE_DEPLOYTIMEOUT=300s
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jjperugachi/fabric-samples/config:/etc/hyperledger/fabric
      - /home/jjperugachi/fabric-samples/test-network/organizations/peerOrganizations/orgcontraloria.example.com/peers/peer0.orgcontraloria.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/jjperugachi/fabric-samples/test-network/organizations/peerOrganizations/orgcontraloria.example.com/peers/peer0.orgcontraloria.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.orgcontraloria.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
    networks:
      - test
